// Code generated by mockery v1.0.0. DO NOT EDIT.

package service

import context "context"
import mock "github.com/stretchr/testify/mock"

// MockHealthServiceInterface is an autogenerated mock type for the HealthServiceInterface type
type MockHealthServiceInterface struct {
	mock.Mock
}

// DBHealthCheck provides a mock function with given fields: ctx
func (_m *MockHealthServiceInterface) DBHealthCheck(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *MockHealthServiceInterface) HealthCheck(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
