// Code generated by mockery v1.0.0. DO NOT EDIT.

package infrastructure

import mock "github.com/stretchr/testify/mock"
import mongo "github.com/mongodb/mongo-go-driver/mongo"

// MockMongoStore is an autogenerated mock type for the MongoStore type
type MockMongoStore struct {
	mock.Mock
}

// DB provides a mock function with given fields:
func (_m *MockMongoStore) DB() *mongo.Database {
	ret := _m.Called()

	var r0 *mongo.Database
	if rf, ok := ret.Get(0).(func() *mongo.Database); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Database)
		}
	}

	return r0
}

// DatabaseName provides a mock function with given fields:
func (_m *MockMongoStore) DatabaseName() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Session provides a mock function with given fields:
func (_m *MockMongoStore) Session() *mongo.Client {
	ret := _m.Called()

	var r0 *mongo.Client
	if rf, ok := ret.Get(0).(func() *mongo.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Client)
		}
	}

	return r0
}
